import type { Metadata } from "next";
import "../globals.css";
import ReduxProvider from "@/redux/Provider";
import Sidebar from "@/components/common/sidebar";

export const metadata: Metadata = {
  title: "Global Caring",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <div className="flex">
        <Sidebar />
        {children}
      </div>
    </ReduxProvider>
  );
}
